# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    node_manager:
      repo: "WhatsARanjit/node_manager"
      ref: "0.7.3"
    ruby_task_helper:
      repo: "puppetlabs/ruby_task_helper"
      ref: "0.5.1"
